# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "987f2b0816f08d00f9c048632fa505ae"
application_url = "https://d38b8c785eaa.ngrok.app/auth/shopify/login"
embedded = true
name = "Charity APP"
handle = "charity-app-6"

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  uri = "https://d38b8c785eaa.ngrok.app/gdpr/customer_data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "https://d38b8c785eaa.ngrok.app/gdpr/customer_redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "https://d38b8c785eaa.ngrok.app/gdpr/shop_redact"
  compliance_topics = [ "shop/redact" ]

[auth]
redirect_urls = [ "https://d38b8c785eaa.ngrok.app/auth/shopify/callback" ]

[pos]
embedded = false

[build]
dev_store_url = "development-store-basecamp.myshopify.com"
include_config_on_deploy = true
