# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ef9f352ccf21b6f051d0da27bc6378c8"
application_url = "https://ummah-bazar-926d98569447.herokuapp.com/auth/shopify/login"
embedded = true
name = "Ummah Bazar"
handle = "charity-app-6"

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  uri = "https://ummah-bazar-926d98569447.herokuapp.com/gdpr/customer_data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "https://ummah-bazar-926d98569447.herokuapp.com/gdpr/customer_redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "https://ummah-bazar-926d98569447.herokuapp.com/gdpr/shop_redact"
  compliance_topics = [ "shop/redact" ]

[auth]
redirect_urls = [ "https://ummah-bazar-926d98569447.herokuapp.com/auth/shopify/callback" ]

[pos]
embedded = false

[build]
dev_store_url = "development-store-basecamp.myshopify.com"
include_config_on_deploy = true
